/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Be9OcjEeRN8
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
} from "@/components/ui/table";
import { Pagination } from "@/components/ui/pagination";
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import Chat from "./chat";

export function UpdatedAiDashboard() {
  return (
    <div className="flex flex-col w-full min-h-screen">
      <Chat />
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
        <Link
          className="flex items-center gap-2 text-lg font-semibold sm:text-base mr-4"
          href="#"
        >
          <FrameIcon className="w-6 h-6" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <nav className="hidden font-medium sm:flex flex-row items-center gap-5 text-sm lg:gap-6">
          <Link className="font-bold" href="#">
            Dashboard
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Evaluations
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Models
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Datasets
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Settings
          </Link>
        </nav>
        <div className="flex items-center w-full gap-4 md:ml-auto md:gap-2 lg:gap-4">
          <Button className="rounded-full ml-auto" size="icon" variant="ghost">
            <img
              alt="Avatar"
              className="rounded-full border"
              height="32"
              src="/placeholder.svg"
              style={{
                aspectRatio: "32/32",
                objectFit: "cover",
              }}
              width="32"
            />
            <span className="sr-only">Toggle user menu</span>
          </Button>
        </div>
      </header>
      <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] bg-gray-100/40 flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10 dark:bg-gray-800/40">
        <div className="max-w-6xl w-full mx-auto grid gap-2">
          <h1 className="font-semibold text-3xl">Dashboard</h1>
        </div>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl w-full mx-auto">
          <Card>
            <CardHeader>
              <CardTitle>Total Evaluations</CardTitle>
              <CardDescription>
                The total number of AI model evaluations performed.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="text-4xl font-bold">125</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Top Performing Model</CardTitle>
              <CardDescription>
                The AI model with the highest average evaluation score.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-2">
                <div className="text-4xl font-bold">GPT-3</div>
                <div className="flex items-center gap-0.5">
                  <StarIcon className="w-5 h-5 fill-gray-900 dark:fill-gray-50" />
                  <StarIcon className="w-5 h-5 fill-gray-900 dark:fill-gray-50" />
                  <StarIcon className="w-5 h-5 fill-gray-900 dark:fill-gray-50" />
                  <StarIcon className="w-5 h-5 fill-gray-900 dark:fill-gray-50" />
                  <StarIcon className="w-5 h-5 fill-gray-100 stroke-gray-500 dark:fill-gray-800 dark:stroke-gray-400" />
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Latest Evaluation</CardTitle>
              <CardDescription>
                The most recent AI model evaluation performed.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-2">
                <div className="text-4xl font-bold">Chinchilla</div>
                <div className="text-2xl text-gray-500 dark:text-gray-400">
                  9.1
                </div>
              </div>
              <div className="text-sm text-gray-500 dark:text-gray-400">
                2022-11-05
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="container mx-auto px-4 py-8 md:px-6 lg:px-8">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-2xl font-bold">AI Evaluations</h2>
            <div className="relative w-full max-w-md">
              <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500 dark:text-gray-400" />
              <Input
                className="w-full pl-10 pr-4 py-2 rounded-md bg-white shadow-sm dark:bg-gray-800 dark:text-gray-200"
                placeholder="Search evaluations..."
                type="search"
              />
            </div>
          </div>
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Model</TableHead>
                  <TableHead>Score</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell>GPT-3</TableCell>
                  <TableCell>9.2</TableCell>
                  <TableCell>2023-04-15</TableCell>
                  <TableCell className="text-right">
                    <Button size="sm" variant="outline">
                      View Details
                    </Button>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>DALL-E 2</TableCell>
                  <TableCell>8.7</TableCell>
                  <TableCell>2023-03-28</TableCell>
                  <TableCell className="text-right">
                    <Button size="sm" variant="outline">
                      View Details
                    </Button>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Whisper</TableCell>
                  <TableCell>9.0</TableCell>
                  <TableCell>2023-02-12</TableCell>
                  <TableCell className="text-right">
                    <Button size="sm" variant="outline">
                      View Details
                    </Button>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Stable Diffusion</TableCell>
                  <TableCell>8.5</TableCell>
                  <TableCell>2023-01-30</TableCell>
                  <TableCell className="text-right">
                    <Button size="sm" variant="outline">
                      View Details
                    </Button>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Midjourney</TableCell>
                  <TableCell>8.9</TableCell>
                  <TableCell>2022-12-20</TableCell>
                  <TableCell className="text-right">
                    <Button size="sm" variant="outline">
                      View Details
                    </Button>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Chinchilla</TableCell>
                  <TableCell>9.1</TableCell>
                  <TableCell>2022-11-05</TableCell>
                  <TableCell className="text-right">
                    <Button size="sm" variant="outline">
                      View Details
                    </Button>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>LLaMA</TableCell>
                  <TableCell>8.8</TableCell>
                  <TableCell>2022-10-18</TableCell>
                  <TableCell className="text-right">
                    <Button size="sm" variant="outline">
                      View Details
                    </Button>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Megatron-LM</TableCell>
                  <TableCell>8.6</TableCell>
                  <TableCell>2022-09-22</TableCell>
                  <TableCell className="text-right">
                    <Button size="sm" variant="outline">
                      View Details
                    </Button>
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
          <div className="flex justify-end mt-6">
            <Pagination />
          </div>
        </div>
        <div className="container mx-auto px-4 py-8 md:px-6 lg:px-8 flex-1 flex flex-col">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-2xl font-bold">AI Chatbot</h2>
            <div className="relative w-full max-w-md">
              <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500 dark:text-gray-400" />
              <Input
                className="w-full pl-10 pr-4 py-2 rounded-md bg-white shadow-sm dark:bg-gray-800 dark:text-gray-200"
                placeholder="Ask the chatbot a question..."
                type="search"
              />
            </div>
          </div>
          <div className="flex-1 flex flex-col gap-4 overflow-y-auto">
            <div className="bg-white dark:bg-gray-800 rounded-lg p-4 shadow-sm flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <Avatar className="w-8 h-8 border">
                  <AvatarImage alt="Chatbot" src="/placeholder-user.jpg" />
                  <AvatarFallback>CB</AvatarFallback>
                </Avatar>
                <div className="font-semibold">Chatbot</div>
              </div>
              <div>
                Hello! I'm an AI chatbot created to assist you with your
                questions about AI model evaluations. How can I help you today?
              </div>
            </div>
            <div className="bg-gray-100 dark:bg-gray-700 rounded-lg p-4 shadow-sm flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <Avatar className="w-8 h-8 border">
                  <AvatarImage alt="User" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="font-semibold">John Doe</div>
              </div>
              <div>
                Hi chatbot, can you tell me more about the top performing AI
                model in our dashboard?
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg p-4 shadow-sm flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <Avatar className="w-8 h-8 border">
                  <AvatarImage alt="Chatbot" src="/placeholder-user.jpg" />
                  <AvatarFallback>CB</AvatarFallback>
                </Avatar>
                <div className="font-semibold">Chatbot</div>
              </div>
              <div>
                Certainly! The top performing AI model in our dashboard is
                GPT-3. It has an average evaluation score of 9.2, which is the
                highest among all the models we've tested. GPT-3 is a large
                language model developed by OpenAI that has shown impressive
                performance on a variety of natural language processing tasks.
              </div>
            </div>
            <div className="bg-gray-100 dark:bg-gray-700 rounded-lg p-4 shadow-sm flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <Avatar className="w-8 h-8 border">
                  <AvatarImage alt="User" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="font-semibold">John Doe</div>
              </div>
              <div>
                That's great to hear. Can you also tell me about the latest
                evaluation we've performed?
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg p-4 shadow-sm flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <Avatar className="w-8 h-8 border">
                  <AvatarImage alt="Chatbot" src="/placeholder-user.jpg" />
                  <AvatarFallback>CB</AvatarFallback>
                </Avatar>
                <div className="font-semibold">Chatbot</div>
              </div>
              <div>
                The latest AI model evaluation we've performed is on the
                Chinchilla model, which received a score of 9.1. Chinchilla is a
                large language model developed by DeepMind that has shown
                impressive performance on a variety of natural language tasks.
                The evaluation was conducted on 2022-11-05.
              </div>
            </div>
            <div className="bg-gray-100 dark:bg-gray-700 rounded-lg p-4 shadow-sm flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <Avatar className="w-8 h-8 border">
                  <AvatarImage alt="User" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="font-semibold">John Doe</div>
              </div>
              <div>
                That's very helpful, thank you. One last question - can you
                provide an overview of the AI evaluations table in the
                dashboard?
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg p-4 shadow-sm flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <Avatar className="w-8 h-8 border">
                  <AvatarImage alt="Chatbot" src="/placeholder-user.jpg" />
                  <AvatarFallback>CB</AvatarFallback>
                </Avatar>
                <div className="font-semibold">Chatbot</div>
              </div>
              <div>
                Certainly! The AI Evaluations table in the dashboard provides a
                summary of the key AI models we've tested, including their
                evaluation scores and the dates the evaluations were performed.
                The table shows the top performing models, with GPT-3 leading
                the pack with a score of 9.2. The most recent evaluation was for
                the Chinchilla model, which scored 9.1 on 2022-11-05. Users can
                search the evaluations and view the details of each model by
                clicking the "View Details" button.
              </div>
            </div>
            <div className="bg-gray-100 dark:bg-gray-700 rounded-lg p-4 shadow-sm flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <Avatar className="w-8 h-8 border">
                  <AvatarImage alt="User" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="font-semibold">John Doe</div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

function FrameIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="22" x2="2" y1="6" y2="6" />
      <line x1="22" x2="2" y1="18" y2="18" />
      <line x1="6" x2="6" y1="2" y2="22" />
      <line x1="18" x2="18" y1="2" y2="22" />
    </svg>
  );
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  );
}
